name: review
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # UI & Media
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.3
  video_player: ^2.8.2
  fl_chart: ^0.66.0
  reactive_forms: ^17.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0

  # Utility
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true